### ISSUE TITLE
Options Invisible When Running in Steam Deck Game Mode (Gamescope)

### ISSUE THREAD

**Issue by KrisCris** [Cloudef/elden-proton#6]
<img width="650" alt="image" src="https://github.com/Cloudef/elden-proton/assets/38860226/eeec8215-ac1f-4e0e-9fdf-95ccc04be8b2">

Not sure how to fix this, I tried specifying `--height` for Zenity, but it only made the window larger, not the actual list. (And it seems the scrollbar is not working for me)

**Comment by Cloudef** [comment]
Probably related to https://github.com/ValveSoftware/steam-runtime/issues/104

**Comment by Cloudef** [comment]
I can reproduce this with
`ER_PATH=tmp NIXPKGS_ALLOW_UNFREE=1 nix run --impure nixpkgs#steam-run -- ~/.steam/steam/ubuntu12_32/steam-runtime/run.sh bash elden-proton.bash true` on nixos, I'll see if it can be workarounded somehow

**Comment by Cloudef** [comment]
Okay should be fixed now, can you test?

**Comment by KrisCris** [comment]
Hmm, the game is not launching (desktop mode is fine). 

FYI my launch option is: `bash "/home/deck/Applications/elden-proton/elden-proton.bash" %command%`.

**Comment by Cloudef** [comment]
what if you prepend export to line 18?

**Comment by Cloudef** [comment]
Maybe you can use 
`bash -x "/home/deck/Applications/elden-proton/elden-proton.bash" %command% > /tmp/elden-proton.log`
and post the /tmp/elden-proton.log here

**Comment by KrisCris** [comment]
> what if you prepend export to line 18?

still no luck

> post the /tmp/elden-proton.log here

the `.log` file is created, but it is empty.

**Comment by Cloudef** [comment]
Sorry, should be
`bash -x "/home/deck/Applications/elden-proton/elden-proton.bash" %command% 2>/tmp/elden-proton.log`

**Comment by KrisCris** [comment]
[elden-proton.log](https://github.com/Cloudef/elden-proton/files/13749202/elden-proton.log)

**Comment by Cloudef** [comment]
what happens if you  do 
`SYSTEM_ZENITY=/usr/bin/zenity bash "/home/deck/Applications/elden-proton/elden-proton.bash" %command%` ?

**Comment by Cloudef** [comment]
Or `STEAM_ZENITY=/usr/bin/zenity`

**Comment by KrisCris** [comment]
> SYSTEM_ZENITY=/usr/bin/zenity

[elden-proton.log](https://github.com/Cloudef/elden-proton/files/13749307/elden-proton.log)

> STEAM_ZENITY=/usr/bin/zenity

It works

**Comment by Cloudef** [comment]
Ok pushed a fix that should fix it for all possible setups.

**Comment by KrisCris** [comment]
Tested, works for me. Thanks so much!

**Comment by Cloudef** [comment]
Thank you for testing :+1:
